/*
 * Copyright (c) 2024 Tenstorrent AI ULC
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef TENSTORRENT_JTAG_BOOTROM_BH_REG_DEF_H_
#define TENSTORRENT_JTAG_BOOTROM_BH_REG_DEF_H_

#define ROM_MEMORY_MEM_BASE_ADDR                0x80000000
#define RESET_UNIT_REFCLK_CNT_LO_REG_ADDR       0x800300E0
#define RESET_UNIT_ARC_MISC_CNTL_REG_ADDR       0x80030100
#define RESET_UNIT_SYS_JTAG_PAD_CNTL_REG_ADDR   0x80030190
#define RESET_UNIT_GPIO_PAD_TRIEN_CNTL_REG_ADDR 0x800301A0
/* SYS_JTAG_PAD_CNTL 5-bit fields, bit 0 = TCK (see RESET_UNIT_SYS_JTAG_PAD_DATA). */
#define SYS_JTAG_TCK_PUEN (1u << 5)
#define SYS_JTAG_TCK_PDEN (1u << 10)
#define RESET_UNIT_MEM_REPAIR_CNTL_REG_ADDR     0x800300C0
#define RESET_UNIT_MEM_REPAIR_STATUS_REG_ADDR   0x800300C4

#endif
